Data source - https://www.football-data.co.uk/

In [2]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

df_21 = pd.read_csv('data/2020-2021.csv')
df_22 = pd.read_csv('data/2021-2022.csv')
df_23 = pd.read_csv('data/2022-2023.csv')
df_24 = pd.read_csv('data/2023-2024.csv')


# Join the two seasons together

df = pd.concat([df_24, df_23, df_22, df_21], ignore_index=True)
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,B365>2.5,B365<2.5,P>2.5,P<2.5,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,AHh,B365AHH,B365AHA,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,B365CH,B365CD,B365CA,BWCH,BWCD,BWCA,IWCH,IWCD,IWCA,PSCH,PSCD,PSCA,WHCH,WHCD,WHCA,VCCH,VCCD,VCCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,11/08/2023,20:00,Burnley,Man City,0,3,A,0,2,A,C Pawson,6,17,1,8,11,8,6,5,0,0,1,0,8.00,5.5,1.33,8.75,5.25,1.34,8.00,5.50,1.35,8.58,5.51,1.37,8.00,5.0,1.25,9.50,5.25,1.33,9.50,5.68,1.39,9.02,5.35,1.35,1.67,2.20,1.68,2.29,1.71,2.40,1.65,2.27,1.50,1.86,2.07,1.86,2.07,1.93,2.09,1.85,2.03,9.00,5.25,1.33,8.75,5.25,1.33,8.50,5.25,1.35,9.62,5.81,1.33,7.50,4.6,1.29,10.50,5.25,1.3,10.50,5.81,1.36,9.27,5.45,1.33,1.67,2.20,1.65,2.35,1.73,2.45,1.64,2.28,1.50,1.95,1.98,1.95,1.97,NaN,NaN,1.92,1.95
1,E0,12/08/2023,12:30,Arsenal,Nott'm Forest,2,1,H,2,0,H,M Oliver,15,6,7,2,12,12,8,3,2,2,0,0,1.18,7.0,15.00,1.17,7.50,15.50,1.20,7.25,14.00,1.18,7.86,15.67,1.12,6.5,12.00,1.14,7.50,17.00,1.21,8.50,17.50,1.18,7.64,15.67,1.44,2.75,1.42,2.93,1.45,2.98,1.42,2.85,-2.00,1.88,2.02,1.88,2.01,1.91,2.06,1.87,1.99,1.18,7.00,15.00,1.18,7.00,14.50,1.20,7.00,14.00,1.19,8.00,16.00,1.12,6.5,12.00,1.22,7.00,13.0,1.22,8.40,19.00,1.19,7.43,15.98,1.50,2.63,1.49,2.65,1.52,2.79,1.49,2.63,-2.00,1.95,1.98,1.93,1.97,2.01,2.09,1.95,1.92
2,E0,12/08/2023,15:00,Bournemouth,West Ham,1,1,D,0,0,D,P Bankes,14,16,5,3,9,14,10,4,1,4,0,0,2.70,3.4,2.55,2.65,3.40,2.55,2.70,3.45,2.60,2.70,3.47,2.71,2.62,3.2,2.30,2.63,3.30,2.63,2.80,3.62,2.75,2.69,3.44,2.64,1.90,2.00,1.90,1.99,1.95,2.03,1.88,1.94,0.00,1.95,1.95,1.95,1.95,1.98,1.99,1.94,1.92,2.63,3.50,2.60,2.65,3.50,2.50,2.60,3.50,2.60,2.75,3.60,2.63,2.50,3.2,2.45,2.63,3.50,2.6,2.88,3.67,2.70,2.70,3.53,2.59,1.73,2.10,1.76,2.18,1.83,2.23,1.74,2.12,0.00,2.02,1.91,2.01,1.92,2.06,1.96,1.96,1.91
3,E0,12/08/2023,15:00,Brighton,Luton,4,1,H,1,0,H,D Coote,27,9,12,3,11,12,6,7,2,2,0,0,1.33,5.5,9.00,1.32,5.50,9.00,1.35,5.25,8.50,1.33,5.65,9.61,1.25,4.6,8.50,1.29,5.25,10.00,1.36,6.00,10.50,1.33,5.52,9.61,1.62,2.30,1.62,2.40,1.65,2.45,1.61,2.34,-1.50,1.95,1.95,1.95,1.95,1.98,2.00,1.93,1.93,1.25,6.50,11.00,1.26,6.00,11.00,1.30,5.50,9.50,1.27,6.36,11.36,1.22,5.5,9.00,1.25,5.75,13.0,1.34,6.59,13.00,1.28,5.99,10.91,1.53,2.50,1.56,2.54,1.62,2.66,1.55,2.48,-1.75,2.01,1.92,2.00,1.91,2.14,1.93,2.00,1.86
4,E0,12/08/2023,15:00,Everton,Fulham,0,1,A,0,0,D,S Attwell,19,9,9,2,12,6,10,4,0,2,0,0,2.20,3.4,3.30,2.20,3.40,3.25,2.25,3.40,3.25,2.27,3.45,3.35,2.10,3.2,3.00,2.20,3.30,3.25,2.30,3.57,3.45,2.24,3.43,3.30,2.01,1.89,2.00,1.89,2.04,1.92,1.97,1.86,-0.25,1.93,1.97,1.95,1.95,1.97,2.00,1.92,1.93,2.30,3.20,3.20,2.35,3.20,3.10,2.35,3.25,3.15,2.39,3.32,3.30,2.10,3.2,3.00,2.38,3.20,3.2,2.42,3.42,3.56,2.32,3.28,3.27,2.10,1.73,2.23,1.72,2.26,1.81,2.17,1.71,-0.25,2.06,1.87,2.04,1.88,2.08,1.99,1.98,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1418,E0,23/05/2021,16:00,Liverpool,Crystal Palace,2,0,H,1,0,H,C Pawson,19,5,5,4,10,8,14,1,2,2,0,0,1.14,8.5,15.00,1.16,8.00,16.50,1.15,8.25,16.00,1.16,8.73,18.32,1.15,8.0,17.00,1.17,7.50,17.00,1.19,9.00,20.00,1.16,8.28,17.35,1.36,3.20,1.48,2.63,1.41,3.25,1.37,3.10,-2.25,2.00,1.90,1.99,1.92,2.03,1.96,1.98,1.90,1.14,8.50,15.00,1.16,8.00,16.50,1.15,8.25,16.00,1.19,8.34,15.00,1.15,8.0,17.00,1.17,8.00,17.0,1.20,9.50,18.50,1.16,8.57,16.09,1.28,3.75,1.48,2.63,1.35,3.76,1.31,3.49,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00
1419,E0,23/05/2021,16:00,Man City,Everton,5,0,H,2,0,H,M Oliver,21,8,11,3,8,10,7,5,2,2,0,0,1.44,5.0,6.50,1.44,5.00,6.50,1.47,4.90,6.00,1.43,5.09,7.24,1.44,4.8,7.00,1.45,4.60,7.00,1.48,5.25,7.40,1.44,4.94,6.83,1.61,2.30,1.61,2.42,1.68,2.43,1.62,2.31,-1.25,2.01,1.89,1.98,1.93,2.05,1.93,2.00,1.88,1.30,6.00,9.00,1.30,6.00,9.00,1.30,6.25,8.50,1.28,6.28,10.34,1.30,5.8,9.50,1.30,5.75,9.0,1.32,6.65,11.25,1.30,6.12,9.60,1.44,2.75,1.53,2.63,1.50,2.96,1.45,2.77,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85
1420,E0,23/05/2021,16:00,Sheffield United,Burnley,1,0,H,1,0,H,K Friend,12,10,3,3,11,1,8,9,3,1,0,0,2.80,3.6,2.40,2.80,3.60,2.40,2.85,3.60,2.40,2.87,3.74,2.43,2.80,3.5,2.45,2.88,3.50,2.40,2.90,3.76,2.48,2.84,3.63,2.41,1.72,2.10,1.74,2.18,1.80,2.21,1.74,2.12,0.25,1.79,2.11,1.81,2.11,1.82,2.13,1.79,2.11,2.80,3.40,2.50,2.75,3.50,2.50,2.75,3.40,2.55,2.85,3.45,2.58,2.88,3.5,2.40,2.80,3.50,2.5,3.08,3.67,2.63,2.80,3.47,2.53,1.80,2.00,1.86,2.03,1.89,2.17,1.79,2.05,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84
1421,E0,23/05/2021,16:00,West Ham,Southampton,3,0,H,2,0,H,M Atkinson,14,17,7,5,5,9,2,3,0,3,0,0,1.65,4.0,5.00,1.72,4.00,4.60,1.70,4.10,4.60,1.74,3.99,5.03,1.70,3.9,4.80,1.67,4.10,4.80,1.76,4.18,5.04,1.72,4.00,4.76,1.61,2.30,1.63,2.40,1.70,2.40,1.63,2.31,-0.75,1.91,1.99,1.94,1.98,1.97,2.02,1.92,1.96,1.75,3.90,4.50,1.78,3.75,4.50,1.77,3.85,4.40,1.79,3.94,4.75,1.75,3.8,4.60,1.80,3.80,4.6,1.83,4.00,4.92,1.78,3.85,4.57,1.72,2.10,1.80,2.11,1.80,2.31,1.73,2.14,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89
1422,E0,23/05/2021,16:00,Wolves,Man United,1,2,A,1,2,A,M Dean,14,9,4,4,14,3,6,2,4,1,0,0,2.50,3.5,2.70,2.50,3.60,2.70,2.55,3.60,2.65,2.59,3.78,2.70,2.55,3.5,2.70,2.50,3.50,2.75,2.63,3.78,2.81,2.53,3.63,2.69,1.72,2.10,1.72,2.22,1.81,2.26,1.74,2.13,0.00,1.90,2.00,1.92,2.01,1.93,2.05,1.88,1.99,2.25,3.40,3.20,2.30,3.25,3.20,2.30,3.15,3.35,2.48,3.19,3.28,2.25,3.4,3.20,2.30,3.20,3.4,2.52,3.73,3.40,2.34,3.25,3.26,2.37,1.57,2.49,1.59,2.49,1.75,2.32,1.62,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88

# Selecting only match related columns. 

- Match Statistics (where available)
- Attendance = Crowd Attendance
- Referee = Match Referee
- HS = Home Team Shots
- AS = Away Team Shots
- HST = Home Team Shots on Target
- AST = Away Team Shots on Target
- HHW = Home Team Hit Woodwork
- AHW = Away Team Hit Woodwork
- HC = Home Team Corners
- AC = Away Team Corners
- HF = Home Team Fouls Committed
- AF = Away Team Fouls Committed
- HFKC = Home Team Free Kicks Conceded
- AFKC = Away Team Free Kicks Conceded
- HO = Home Team Offsides
- AO = Away Team Offsides
- HY = Home Team Yellow Cards
- AY = Away Team Yellow Cards
- HR = Home Team Red Cards
- AR = Away Team Red Cards
- HBP = Home Team Bookings Points (10 = yellow, 25 = red)
- ABP = Away Team Bookings Points (10 = yellow, 25 = red)

In [3]:
df = df[df.columns[:24]].copy()
df.loc[:,'Day'] = df['Date'].apply(lambda x:x.split('/')[0])
df.loc[:,'Month'] = df['Date'].apply(lambda x:x.split('/')[1])
df.loc[:,'Year'] = df['Date'].apply(lambda x:x.split('/')[2])
df.loc[:,'Hour'] = df['Time'].apply(lambda x:x.split(":")[0])
df.loc[:,'Min'] = df['Time'].apply(lambda x:x.split(":")[1])
df = df.drop(columns = ['Date', 'Time'])
df = df.sort_values(by= ['Year', 'Month', 'Day', 'Hour']).reset_index(drop = True)
df

,Div,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,Day,Month,Year,Hour,Min
0,E0,Fulham,Arsenal,0,3,A,0,1,A,C Kavanagh,5,13,2,6,12,12,2,3,2,2,0,0,12,09,2020,12,30
1,E0,Crystal Palace,Southampton,1,0,H,1,0,H,J Moss,5,9,3,5,14,11,7,3,2,1,0,0,12,09,2020,15,00
2,E0,Liverpool,Leeds,4,3,H,3,2,H,M Oliver,22,6,6,3,9,6,9,0,1,0,0,0,12,09,2020,17,30
3,E0,West Ham,Newcastle,0,2,A,0,0,D,S Attwell,15,15,3,2,13,7,8,7,2,2,0,0,12,09,2020,20,00
4,E0,West Brom,Leicester,0,3,A,0,0,D,A Taylor,7,13,1,7,12,9,2,5,1,1,0,0,13,09,2020,14,00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1418,E0,Bournemouth,Luton,4,3,H,0,3,A,S Allison,24,8,10,4,16,11,11,3,1,2,0,0,13,03,2024,19,30
1419,E0,Burnley,Brentford,2,1,H,1,0,H,D Bond,17,9,6,5,14,17,5,4,2,4,0,1,16,03,2024,15,00
1420,E0,Luton,Nott'm Forest,1,1,D,0,1,A,D England,10,16,4,6,10,17,6,7,1,2,0,0,16,03,2024,15,00
1421,E0,Fulham,Tottenham,3,0,H,1,0,H,R Jones,16,14,7,5,9,10,4,5,2,3,0,0,16,03,2024,17,30
1422,E0,West Ham,Aston Villa,1,1,D,1,0,H,J Gillett,13,13,5,5,13,12,7,11,3,3,0,0,17,03,2024,14,00

In [4]:
# first part we need:
# 1. A row for each match, from the pespective of both the home and away team.
# 2. A column called team_playing
# 3. A column for opponent

df['team_playing'] = df['HomeTeam']
df['opponent'] = df['AwayTeam']

df2 = df.copy()
df2['team_playing'] = df2['AwayTeam']
df2['opponent'] = df2['HomeTeam']

In [5]:
# we need:
# Columns describing:
# 1. What the team_playing did. We will use these columns to compute rolling statistics of the team playing.
# 2. Columns describing what the opponent did? Yes because does that represent the team_playing, and how oppositions have done against them right?
#  

df = df[['team_playing', 'opponent', 'HomeTeam', 'AwayTeam', 'FTHG', 'HTHG', 'HS', 'HST', 'HF', 'HC', 'HY', 'HR', 
        'Day', 'Month', 'Year', 'Hour',
        'FTAG', 'HTAG', 'AS', 'AST', 'AF', 'AC', 'AY', 'AR', 'FTR', 'Referee']]

df2 = df2[['team_playing', 'opponent','HomeTeam', 'AwayTeam','FTAG', 'HTAG', 'AS', 'AST', 'AF', 'AC', 'AY', 'AR', 
            'Day', 'Month', 'Year', 'Hour',
            'FTHG', 'HTHG', 'HS', 'HST', 'HF', 'HC', 'HY', 'HR', 'FTR', 'Referee']]


# We have two datasets. Each containing a team_playing column. df is when the team_playing is the home team and df2 is when 
# the team playing is the away team.

# We need to convert these column names from home and way to team_playing stats and opponent stats.

In [6]:
# First we change the home team. So we need to rename the columns that represent the home teams to say TP for team playing.


df = df.rename(columns = {'FTHG':'FT_TP_G', # goals for the team playing
            'HTHG':'HT_TP_G', 
            'HS':'TP_S', 
            'HST':'TP_ST', 
            'HF':'TP_F',
            'HC': 'TP_C',
            'HY':'TP_Y', 
            'HR':'TP_R',
            'FTAG':'FT_OP_G', 
            'HTAG':'HT_OP_G', 
            'AS':'OP_S', 
            'AST':'OP_ST', 
            'AF':'OP_F',
            'AC': 'OP_C',
            'AY':'OP_Y', 
            'AR':'OP_R'})
df

,team_playing,opponent,HomeTeam,AwayTeam,FT_TP_G,HT_TP_G,TP_S,TP_ST,TP_F,TP_C,TP_Y,TP_R,Day,Month,Year,Hour,FT_OP_G,HT_OP_G,OP_S,OP_ST,OP_F,OP_C,OP_Y,OP_R,FTR,Referee
0,Fulham,Arsenal,Fulham,Arsenal,0,0,5,2,12,2,2,0,12,09,2020,12,3,1,13,6,12,3,2,0,A,C Kavanagh
1,Crystal Palace,Southampton,Crystal Palace,Southampton,1,1,5,3,14,7,2,0,12,09,2020,15,0,0,9,5,11,3,1,0,H,J Moss
2,Liverpool,Leeds,Liverpool,Leeds,4,3,22,6,9,9,1,0,12,09,2020,17,3,2,6,3,6,0,0,0,H,M Oliver
3,West Ham,Newcastle,West Ham,Newcastle,0,0,15,3,13,8,2,0,12,09,2020,20,2,0,15,2,7,7,2,0,A,S Attwell
4,West Brom,Leicester,West Brom,Leicester,0,0,7,1,12,2,1,0,13,09,2020,14,3,0,13,7,9,5,1,0,A,A Taylor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1418,Bournemouth,Luton,Bournemouth,Luton,4,0,24,10,16,11,1,0,13,03,2024,19,3,3,8,4,11,3,2,0,H,S Allison
1419,Burnley,Brentford,Burnley,Brentford,2,1,17,6,14,5,2,0,16,03,2024,15,1,0,9,5,17,4,4,1,H,D Bond
1420,Luton,Nott'm Forest,Luton,Nott'm Forest,1,0,10,4,10,6,1,0,16,03,2024,15,1,1,16,6,17,7,2,0,D,D England
1421,Fulham,Tottenham,Fulham,Tottenham,3,1,16,7,9,4,2,0,16,03,2024,17,0,0,14,5,10,5,3,0,H,R Jones
1422,West Ham,Aston Villa,West Ham,Aston Villa,1,1,13,5,13,7,3,0,17,03,2024,14,1,0,13,5,12,11,3,0,D,J Gillett

In [7]:
df2 = df2.rename(columns = {'FTHG':'FT_OP_G',  # 
            'HTHG':'HT_OP_G', 
            'HS':'OP_S', 
            'HST':'OP_ST', 
            'HF':'OP_F',
            'HC': 'OP_C',
            'HY':'OP_Y', 
            'HR':'OP_R',
            'FTAG':'FT_TP_G', 
            'HTAG':'HT_TP_G', 
            'AS':'TP_S', 
            'AST':'TP_ST', 
            'AF':'TP_F',
            'AC': 'TP_C',
            'AY':'TP_Y', 
            'AR':'TP_R'})

df2

,team_playing,opponent,HomeTeam,AwayTeam,FT_TP_G,HT_TP_G,TP_S,TP_ST,TP_F,TP_C,TP_Y,TP_R,Day,Month,Year,Hour,FT_OP_G,HT_OP_G,OP_S,OP_ST,OP_F,OP_C,OP_Y,OP_R,FTR,Referee
0,Arsenal,Fulham,Fulham,Arsenal,3,1,13,6,12,3,2,0,12,09,2020,12,0,0,5,2,12,2,2,0,A,C Kavanagh
1,Southampton,Crystal Palace,Crystal Palace,Southampton,0,0,9,5,11,3,1,0,12,09,2020,15,1,1,5,3,14,7,2,0,H,J Moss
2,Leeds,Liverpool,Liverpool,Leeds,3,2,6,3,6,0,0,0,12,09,2020,17,4,3,22,6,9,9,1,0,H,M Oliver
3,Newcastle,West Ham,West Ham,Newcastle,2,0,15,2,7,7,2,0,12,09,2020,20,0,0,15,3,13,8,2,0,A,S Attwell
4,Leicester,West Brom,West Brom,Leicester,3,0,13,7,9,5,1,0,13,09,2020,14,0,0,7,1,12,2,1,0,A,A Taylor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1418,Luton,Bournemouth,Bournemouth,Luton,3,3,8,4,11,3,2,0,13,03,2024,19,4,0,24,10,16,11,1,0,H,S Allison
1419,Brentford,Burnley,Burnley,Brentford,1,0,9,5,17,4,4,1,16,03,2024,15,2,1,17,6,14,5,2,0,H,D Bond
1420,Nott'm Forest,Luton,Luton,Nott'm Forest,1,1,16,6,17,7,2,0,16,03,2024,15,1,0,10,4,10,6,1,0,D,D England
1421,Tottenham,Fulham,Fulham,Tottenham,0,0,14,5,10,5,3,0,16,03,2024,17,3,1,16,7,9,4,2,0,H,R Jones
1422,Aston Villa,West Ham,West Ham,Aston Villa,1,0,13,5,12,11,3,0,17,03,2024,14,1,1,13,5,13,7,3,0,D,J Gillett

In [8]:
df_final = pd.concat([df, df2], ignore_index=True)
df_final = df_final.sort_values(by = ['Year', 'Month', 'Day', 'Hour', 'Referee']).reset_index(drop = True)
df_final

,team_playing,opponent,HomeTeam,AwayTeam,FT_TP_G,HT_TP_G,TP_S,TP_ST,TP_F,TP_C,TP_Y,TP_R,Day,Month,Year,Hour,FT_OP_G,HT_OP_G,OP_S,OP_ST,OP_F,OP_C,OP_Y,OP_R,FTR,Referee
0,Fulham,Arsenal,Fulham,Arsenal,0,0,5,2,12,2,2,0,12,09,2020,12,3,1,13,6,12,3,2,0,A,C Kavanagh
1,Arsenal,Fulham,Fulham,Arsenal,3,1,13,6,12,3,2,0,12,09,2020,12,0,0,5,2,12,2,2,0,A,C Kavanagh
2,Crystal Palace,Southampton,Crystal Palace,Southampton,1,1,5,3,14,7,2,0,12,09,2020,15,0,0,9,5,11,3,1,0,H,J Moss
3,Southampton,Crystal Palace,Crystal Palace,Southampton,0,0,9,5,11,3,1,0,12,09,2020,15,1,1,5,3,14,7,2,0,H,J Moss
4,Liverpool,Leeds,Liverpool,Leeds,4,3,22,6,9,9,1,0,12,09,2020,17,3,2,6,3,6,0,0,0,H,M Oliver
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2841,Nott'm Forest,Luton,Luton,Nott'm Forest,1,1,16,6,17,7,2,0,16,03,2024,15,1,0,10,4,10,6,1,0,D,D England
2842,Fulham,Tottenham,Fulham,Tottenham,3,1,16,7,9,4,2,0,16,03,2024,17,0,0,14,5,10,5,3,0,H,R Jones
2843,Tottenham,Fulham,Fulham,Tottenham,0,0,14,5,10,5,3,0,16,03,2024,17,3,1,16,7,9,4,2,0,H,R Jones
2844,West Ham,Aston Villa,West Ham,Aston Villa,1,1,13,5,13,7,3,0,17,03,2024,14,1,0,13,5,12,11,3,0,D,J Gillett
2845,Aston Villa,West Ham,West Ham,Aston Villa,1,0,13,5,12,11,3,0,17,03,2024,14,1,1,13,5,13,7,3,0,D,J Gillett

In [9]:
# create is_home feature.

df_final['is_home'] = (df_final['team_playing'] == df_final['HomeTeam']).astype(int)
df_final

,team_playing,opponent,HomeTeam,AwayTeam,FT_TP_G,HT_TP_G,TP_S,TP_ST,TP_F,TP_C,TP_Y,TP_R,Day,Month,Year,Hour,FT_OP_G,HT_OP_G,OP_S,OP_ST,OP_F,OP_C,OP_Y,OP_R,FTR,Referee,is_home
0,Fulham,Arsenal,Fulham,Arsenal,0,0,5,2,12,2,2,0,12,09,2020,12,3,1,13,6,12,3,2,0,A,C Kavanagh,1
1,Arsenal,Fulham,Fulham,Arsenal,3,1,13,6,12,3,2,0,12,09,2020,12,0,0,5,2,12,2,2,0,A,C Kavanagh,0
2,Crystal Palace,Southampton,Crystal Palace,Southampton,1,1,5,3,14,7,2,0,12,09,2020,15,0,0,9,5,11,3,1,0,H,J Moss,1
3,Southampton,Crystal Palace,Crystal Palace,Southampton,0,0,9,5,11,3,1,0,12,09,2020,15,1,1,5,3,14,7,2,0,H,J Moss,0
4,Liverpool,Leeds,Liverpool,Leeds,4,3,22,6,9,9,1,0,12,09,2020,17,3,2,6,3,6,0,0,0,H,M Oliver,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2841,Nott'm Forest,Luton,Luton,Nott'm Forest,1,1,16,6,17,7,2,0,16,03,2024,15,1,0,10,4,10,6,1,0,D,D England,0
2842,Fulham,Tottenham,Fulham,Tottenham,3,1,16,7,9,4,2,0,16,03,2024,17,0,0,14,5,10,5,3,0,H,R Jones,1
2843,Tottenham,Fulham,Fulham,Tottenham,0,0,14,5,10,5,3,0,16,03,2024,17,3,1,16,7,9,4,2,0,H,R Jones,0
2844,West Ham,Aston Villa,West Ham,Aston Villa,1,1,13,5,13,7,3,0,17,03,2024,14,1,0,13,5,12,11,3,0,D,J Gillett,1
2845,Aston Villa,West Ham,West Ham,Aston Villa,1,0,13,5,12,11,3,0,17,03,2024,14,1,1,13,5,13,7,3,0,D,J Gillett,0

In [18]:
# rename the columns. 

rename_columns = {
    'FT_TP_G': 'team_playing_ft_goals',  # Full-Time Goals by Team Playing
    'HT_TP_G': 'team_playing_ht_goals',  # Half-Time Goals by Team Playing
    'TP_S': 'team_playing_total_shots',  # Total Shots by Team Playing
    'TP_ST': 'team_playing_shots_on_target',  # Shots on Target by Team Playing
    'TP_F': 'team_playing_fouls_committed',  # Fouls Committed by Team Playing
    'TP_C': 'team_playing_corners_won',  # Corners Won by Team Playing
    'TP_Y': 'team_playing_yellow_cards',  # Yellow Cards Received by Team Playing
    'TP_R': 'team_playing_red_cards',  # Red Cards Received by Team Playing
    'FT_OP_G': 'opponent_ft_goals',  # Full-Time Goals by Opponent (Goals Conceded by Team Playing)
    'HT_OP_G': 'opponent_ht_goals',  # Half-Time Goals by Opponent
    'OP_S': 'opponent_total_shots',  # Total Shots by Opponent
    'OP_ST': 'opponent_shots_on_target',  # Shots on Target by Opponent
    'OP_F': 'opponent_fouls_committed',  # Fouls Committed by Opponent (Fouls Won by Team Playing)
    'OP_C': 'opponent_corners_won',  # Corners Won by Opponent
    'OP_Y': 'opponent_yellow_cards',  # Yellow Cards Received by Opponent
    'OP_R': 'opponent_red_cards',  # Red Cards Received by Opponent
}



df_final.rename(columns=rename_columns)

,team_playing,opponent,HomeTeam,AwayTeam,team_playing_ft_goals,team_playing_ht_goals,team_playing_total_shots,team_playing_shots_on_target,team_playing_fouls_committed,team_playing_corners_won,team_playing_yellow_cards,team_playing_red_cards,Day,Month,Year,Hour,opponent_ft_goals,opponent_ht_goals,opponent_total_shots,opponent_shots_on_target,opponent_fouls_committed,opponent_corners_won,opponent_yellow_cards,opponent_red_cards,FTR,Referee,is_home,target
0,Fulham,Arsenal,Fulham,Arsenal,0,0,5,2,12,2,2,0,12,09,2020,12,3,1,13,6,12,3,2,0,A,C Kavanagh,1,0
1,Arsenal,Fulham,Fulham,Arsenal,3,1,13,6,12,3,2,0,12,09,2020,12,0,0,5,2,12,2,2,0,A,C Kavanagh,0,1
2,Crystal Palace,Southampton,Crystal Palace,Southampton,1,1,5,3,14,7,2,0,12,09,2020,15,0,0,9,5,11,3,1,0,H,J Moss,1,1
3,Southampton,Crystal Palace,Crystal Palace,Southampton,0,0,9,5,11,3,1,0,12,09,2020,15,1,1,5,3,14,7,2,0,H,J Moss,0,0
4,Liverpool,Leeds,Liverpool,Leeds,4,3,22,6,9,9,1,0,12,09,2020,17,3,2,6,3,6,0,0,0,H,M Oliver,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2841,Nott'm Forest,Luton,Luton,Nott'm Forest,1,1,16,6,17,7,2,0,16,03,2024,15,1,0,10,4,10,6,1,0,D,D England,0,0
2842,Fulham,Tottenham,Fulham,Tottenham,3,1,16,7,9,4,2,0,16,03,2024,17,0,0,14,5,10,5,3,0,H,R Jones,1,1
2843,Tottenham,Fulham,Fulham,Tottenham,0,0,14,5,10,5,3,0,16,03,2024,17,3,1,16,7,9,4,2,0,H,R Jones,0,0
2844,West Ham,Aston Villa,West Ham,Aston Villa,1,1,13,5,13,7,3,0,17,03,2024,14,1,0,13,5,12,11,3,0,D,J Gillett,1,0
2845,Aston Villa,West Ham,West Ham,Aston Villa,1,0,13,5,12,11,3,0,17,03,2024,14,1,1,13,5,13,7,3,0,D,J Gillett,0,0

In [11]:
# Now we need to create a binary target column that tells us if the team_playing won the match.

df_final['target'] = ((((df_final['is_home']==1) & (df_final['FTR']=='H')) | ((df_final['is_home']==0) & (df_final['FTR']=='A')))).astype(int)
df_final.head(7)

,team_playing,opponent,HomeTeam,AwayTeam,FT_TP_G,HT_TP_G,TP_S,TP_ST,TP_F,TP_C,TP_Y,TP_R,Day,Month,Year,Hour,FT_OP_G,HT_OP_G,OP_S,OP_ST,OP_F,OP_C,OP_Y,OP_R,FTR,Referee,is_home,target
0,Fulham,Arsenal,Fulham,Arsenal,0,0,5,2,12,2,2,0,12,09,2020,12,3,1,13,6,12,3,2,0,A,C Kavanagh,1,0
1,Arsenal,Fulham,Fulham,Arsenal,3,1,13,6,12,3,2,0,12,09,2020,12,0,0,5,2,12,2,2,0,A,C Kavanagh,0,1
2,Crystal Palace,Southampton,Crystal Palace,Southampton,1,1,5,3,14,7,2,0,12,09,2020,15,0,0,9,5,11,3,1,0,H,J Moss,1,1
3,Southampton,Crystal Palace,Crystal Palace,Southampton,0,0,9,5,11,3,1,0,12,09,2020,15,1,1,5,3,14,7,2,0,H,J Moss,0,0
4,Liverpool,Leeds,Liverpool,Leeds,4,3,22,6,9,9,1,0,12,09,2020,17,3,2,6,3,6,0,0,0,H,M Oliver,1,1
5,Leeds,Liverpool,Liverpool,Leeds,3,2,6,3,6,0,0,0,12,09,2020,17,4,3,22,6,9,9,1,0,H,M Oliver,0,0
6,West Ham,Newcastle,West Ham,Newcastle,0,0,15,3,13,8,2,0,12,09,2020,20,2,0,15,2,7,7,2,0,A,S Attwell,1,0

# Feature Engineering

Calculating Rolling Statistics. We want to calculate rolling stats. At the moment, these features are telling us what happened during each particular match. When making predictions we wont know these stats. We want to be able to use what happened in the past to predict future games.

In [12]:
df_grouped = df_final.groupby('team_playing')

#df_final.drop(columns = ['AwayTeam', 'FTR', 'HomeTeam', 'Referee', 'opponent', 'team_playing', 'Day', 'Month', 'Year']).rolling(window = 3, closed = 'left').mean()

# We grouped the data by team_playing. Now we can calculate rolling stats for each team respectivly. 
# We will exclude non numeric columns and time columns.

In [13]:
cols_to_drop = ['AwayTeam', 'FTR', 'HomeTeam', 'Referee', 'opponent', 'team_playing', 'Day', 'Month', 'Year', 'Hour', 'is_home']

window = 3
data = []

for name, group in df_grouped:
    print(name)
    group.sort_values(by = ['Year', 'Month', 'Day', 'Hour', 'Referee']).reset_index(drop = True, inplace=True)
    mean_ = group.drop(columns =cols_to_drop).rolling(window = window, closed = 'left').mean().add_suffix('_rolling_mean')
    sum_ = group.drop(columns =cols_to_drop).rolling(window = window, closed = 'left').sum().add_suffix('_rolling_sum')
    std_ = group.drop(columns =cols_to_drop).rolling(window = window, closed = 'left').std().add_suffix('_rolling_std')
    min_ = group.drop(columns =cols_to_drop).rolling(window = window, closed = 'left').min().add_suffix('_rolling_min')
    max_ = group.drop(columns =cols_to_drop).rolling(window = window, closed = 'left').min().add_suffix('_rolling_max')
    

    d = pd.concat([group[['team_playing', 'opponent', 'is_home', 'target', 'Year', 'Month', 'Day', 'Hour', 'Referee']], mean_, sum_, std_, min_, max_], axis = 1).bfill()
    data.append(d)

Arsenal
Aston Villa
Bournemouth
Brentford
Brighton
Burnley
Chelsea
Crystal Palace
Everton
Fulham
Leeds
Leicester
Liverpool
Luton
Man City
Man United
Newcastle
Norwich
Nott'm Forest
Sheffield United
Southampton
Tottenham
Watford
West Brom
West Ham
Wolves

In [14]:
group

,team_playing,opponent,HomeTeam,AwayTeam,FT_TP_G,HT_TP_G,TP_S,TP_ST,TP_F,TP_C,TP_Y,TP_R,Day,Month,Year,Hour,FT_OP_G,HT_OP_G,OP_S,OP_ST,OP_F,OP_C,OP_Y,OP_R,FTR,Referee,is_home,target
13,Wolves,Sheffield United,Sheffield United,Wolves,2,2,11,4,7,5,1,0,14,09,2020,18,0,0,9,2,13,12,2,0,A,M Dean,0,1
34,Wolves,Man City,Wolves,Man City,1,0,10,1,6,4,0,0,21,09,2020,20,3,2,14,9,8,6,3,0,A,A Marriner,1,0
51,Wolves,West Ham,West Ham,Wolves,0,0,11,2,11,3,1,0,27,09,2020,19,4,1,15,7,7,1,0,0,H,M Atkinson,0,0
68,Wolves,Fulham,Wolves,Fulham,1,0,14,5,15,6,1,0,04,10,2020,14,0,0,10,2,8,2,1,0,H,D England,1,1
95,Wolves,Leeds,Leeds,Wolves,1,0,7,3,12,3,1,0,19,10,2020,20,0,0,13,2,13,8,2,0,A,D Coote,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2744,Wolves,Brentford,Wolves,Brentford,0,0,17,5,11,7,2,0,10,02,2024,15,2,1,9,6,9,4,3,0,A,S Hooper,1,0
2759,Wolves,Tottenham,Tottenham,Wolves,2,1,12,7,13,4,1,0,17,02,2024,15,1,0,15,4,8,10,0,0,A,A Taylor,0,1
2792,Wolves,Sheffield United,Wolves,Sheffield United,1,1,13,2,8,5,2,0,25,02,2024,13,0,0,12,4,4,6,1,0,H,D Bond,1,1
2807,Wolves,Newcastle,Newcastle,Wolves,0,0,12,3,11,5,1,0,02,03,2024,15,3,2,14,7,8,3,0,0,H,T Robinson,0,0
2822,Wolves,Fulham,Wolves,Fulham,2,0,8,3,7,3,2,0,09,03,2024,15,1,0,23,6,11,4,2,0,H,T Harrington,1,1

In [15]:
# creating a top 6 binary feature to indicate if the team_playing or opponent is considered top 6 team.
final_data = pd.concat(data).sort_index()
top_6 = ['Arsenal', 'Liverpool', 'Man City', 'Man United', 'Chelsea', 'Tottenham']
final_data['TP_top6'] = final_data['team_playing'].apply(lambda x:1 if x in top_6 else 0)
final_data['OP_top6'] = final_data['opponent'].apply(lambda x:1 if x in top_6 else 0)

In [16]:
final_data['Date'] = pd.to_datetime(final_data[['Year', 'Month', 'Day', 'Hour']])
final_data.sort_values(by = ['Date', 'Referee'], inplace = True)

In [17]:
final_data = final_data.sort_values(by = ['Year', 'Month', 'Day', 'Hour', 'Referee']).reset_index(drop = True)
final_data.rename(columns={''})

TypeError: 'set' object is not callable

In [ ]:
final_data.shape

(2846, 97)

In [ ]:
final_data.to_csv('data/final_data.csv', index = False)

In [ ]:
# # split this data into training and testing here.
# # Data is sorted by time already. We will take the first 70% for training and the remaining 30% for testing.
# # A more traditional split for splitting data
# split_idx = int(len(final_data) * 0.7)

# # Split the DataFrame into training and testing sets
# train_df = final_data.iloc[:split_idx]
# test_df = final_data.iloc[split_idx:]


# But for this project, I am going to train the models on all the data exepct lasts weeks matches, and then run the predictions for next weeks.

train_df = final_data[final_data['Date']<=pd.Timestamp('2024-03-01')]
test_df = final_data[final_data['Date']>pd.Timestamp('2024-03-01')]

print(train_df.shape)
print(test_df.shape)

# I am going t

(2796, 97)
(50, 97)

In [ ]:
train_df.to_csv('data/train_df.csv', index = False)
test_df.to_csv('data/test_df.csv', index = False)