Data source - https://www.football-data.co.uk/

In [117]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

In [118]:
df_last = pd.read_csv('data/2022-2023.csv')
df_current = pd.read_csv('data/2023-2024.csv')


# Join the two seasons together

df = pd.concat([df_last, df_current], ignore_index=True)
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,PSH,PSD,PSA,WHH,WHD,WHA,VCH,VCD,VCA,MaxH,MaxD,MaxA,AvgH,AvgD,AvgA,B365>2.5,B365<2.5,P>2.5,P<2.5,Max>2.5,Max<2.5,Avg>2.5,Avg<2.5,AHh,B365AHH,B365AHA,PAHH,PAHA,MaxAHH,MaxAHA,AvgAHH,AvgAHA,B365CH,B365CD,B365CA,BWCH,BWCD,BWCA,IWCH,IWCD,IWCA,PSCH,PSCD,PSCA,WHCH,WHCD,WHCA,VCCH,VCCD,VCCA,MaxCH,MaxCD,MaxCA,AvgCH,AvgCD,AvgCA,B365C>2.5,B365C<2.5,PC>2.5,PC<2.5,MaxC>2.5,MaxC<2.5,AvgC>2.5,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,05/08/2022,20:00,Crystal Palace,Arsenal,0,2,A,0,1,A,A Taylor,10,10,2,2,16,11,3,5,1,2,0,0,4.20,3.60,1.85,4.33,3.50,1.87,4.30,3.55,1.85,4.50,3.65,1.89,4.40,3.50,1.83,4.60,3.50,1.87,4.60,3.78,1.95,4.39,3.59,1.88,2.10,1.72,2.14,1.78,2.19,1.91,2.09,1.76,0.50,2.04,1.89,2.03,1.89,2.06,1.91,2.01,1.87,4.50,3.60,1.80,4.50,3.5,1.83,4.40,3.55,1.85,4.58,3.63,1.88,4.80,3.40,1.78,4.75,3.5,1.85,5.01,3.70,1.91,4.56,3.57,1.85,2.10,1.72,2.14,1.78,2.19,1.91,2.08,1.76,0.50,2.09,1.84,2.04,1.88,2.09,1.88,2.03,1.85
1,E0,06/08/2022,12:30,Fulham,Liverpool,2,2,D,1,0,H,A Madley,9,11,3,4,7,9,4,4,2,0,0,0,11.00,6.00,1.25,10.00,5.75,1.28,12.00,5.75,1.27,11.20,6.22,1.28,12.00,5.50,1.27,13.00,6.00,1.25,13.00,6.40,1.31,10.99,6.05,1.28,1.50,2.62,1.50,2.70,1.54,2.76,1.48,2.63,1.75,1.90,2.03,1.91,2.00,1.92,2.04,1.89,1.99,11.00,5.75,1.28,9.25,6.0,1.29,11.00,5.50,1.30,10.50,6.50,1.29,11.00,5.50,1.27,11.50,6.0,1.29,11.95,6.93,1.30,10.33,6.20,1.28,1.50,2.62,1.49,2.77,1.51,3.00,1.47,2.73,1.75,1.90,2.03,1.91,2.02,2.01,2.06,1.89,1.99
2,E0,06/08/2022,15:00,Bournemouth,Aston Villa,2,0,H,1,0,H,P Bankes,7,15,3,2,18,16,5,5,3,3,0,0,3.75,3.50,2.00,3.75,3.40,2.00,3.65,3.45,2.05,3.93,3.58,2.04,3.75,3.30,2.05,3.75,3.30,2.00,4.00,3.66,2.10,3.80,3.50,2.04,2.00,1.80,2.10,1.81,2.10,1.87,2.03,1.80,0.50,1.87,2.06,1.88,2.04,1.88,2.07,1.85,2.04,4.00,3.50,1.95,3.90,3.4,1.95,3.85,3.45,2.00,4.09,3.59,2.00,4.00,3.40,1.95,4.10,3.4,2.00,4.25,3.63,2.06,3.99,3.49,2.00,2.10,1.72,2.13,1.79,2.24,1.81,2.10,1.76,0.50,1.93,2.00,1.93,2.00,1.94,2.04,1.88,2.00
3,E0,06/08/2022,15:00,Leeds,Wolves,2,1,H,1,1,D,R Jones,12,15,4,6,13,9,6,4,2,0,0,0,2.25,3.40,3.20,2.30,3.30,2.95,2.30,3.30,3.15,2.39,3.33,3.30,2.25,3.30,3.20,2.30,3.20,3.10,2.42,3.54,3.30,2.34,3.34,3.18,2.05,1.85,2.09,1.83,2.11,1.87,2.03,1.81,-0.25,2.05,1.88,2.04,1.89,2.06,1.90,2.01,1.87,2.37,3.30,3.00,2.40,3.3,2.75,2.45,3.30,2.95,2.45,3.44,3.09,2.40,3.30,2.90,2.40,3.4,3.00,2.50,3.55,3.18,2.43,3.36,3.02,1.95,1.95,1.96,1.94,2.09,1.96,1.96,1.87,-0.25,2.08,1.85,2.10,1.84,2.14,1.87,2.08,1.81
4,E0,06/08/2022,15:00,Newcastle,Nott'm Forest,2,0,H,0,0,D,S Hooper,23,5,10,0,9,14,11,1,0,3,0,0,1.66,3.80,5.25,1.65,3.80,5.50,1.65,3.80,5.50,1.71,3.74,5.83,1.67,3.70,5.25,1.62,3.70,5.50,1.72,3.96,6.00,1.67,3.80,5.57,2.05,1.85,2.10,1.81,2.10,1.86,2.03,1.81,-0.75,1.87,2.06,1.92,2.01,1.92,2.08,1.86,2.02,1.53,4.00,6.00,1.58,3.9,6.00,1.63,3.80,6.00,1.57,4.22,6.60,1.53,3.90,6.50,1.57,3.9,7.00,1.67,4.30,7.00,1.59,4.07,6.15,1.94,1.96,1.97,1.93,2.06,1.97,1.94,1.89,-1.00,1.97,1.96,1.99,1.93,2.19,1.97,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658,E0,13/03/2024,19:30,Bournemouth,Luton,4,3,H,0,3,A,S Allison,24,8,10,4,16,11,11,3,1,2,0,0,1.50,4.75,5.75,1.50,4.60,5.75,NaN,NaN,NaN,1.51,4.71,6.18,1.44,4.80,5.80,1.45,4.60,6.00,1.55,4.98,6.40,1.50,4.77,6.00,1.44,2.70,1.48,2.75,1.49,2.82,1.47,2.71,-1.25,2.05,1.85,2.06,1.85,2.09,1.90,2.03,1.83,1.53,4.75,5.50,1.51,4.8,5.50,NaN,NaN,NaN,1.53,4.89,5.69,1.53,4.80,5.50,1.50,4.8,5.50,1.57,5.00,6.00,1.52,4.87,5.65,1.40,2.88,1.41,3.04,1.43,3.10,1.40,2.99,-1.00,1.84,2.06,1.85,2.09,1.87,2.13,1.82,2.07
659,E0,16/03/2024,15:00,Burnley,Brentford,2,1,H,1,0,H,D Bond,17,9,6,5,14,17,5,4,2,4,0,1,3.25,3.60,2.15,3.20,3.60,2.15,NaN,NaN,NaN,3.23,3.72,2.20,3.20,3.70,2.10,3.25,3.50,2.10,3.41,3.80,2.21,3.27,3.66,2.16,1.75,2.05,1.78,2.12,1.80,2.17,1.75,2.10,0.25,1.99,1.91,1.98,1.92,2.00,1.94,1.96,1.87,3.10,3.75,2.20,3.10,3.5,2.25,NaN,NaN,NaN,3.18,3.65,2.28,3.10,3.70,2.20,3.13,3.6,2.20,3.27,3.80,2.33,3.12,3.64,2.26,1.70,2.10,1.77,2.16,1.78,2.21,1.74,2.13,0.25,1.95,1.95,1.94,1.98,1.97,2.00,1.91,1.94
660,E0,16/03/2024,15:00,Luton,Nott'm Forest,1,1,D,0,1,A,D England,10,16,4,6,10,17,6,7,1,2,0,0,2.80,3.50,2.45,2.70,3.60,2.45,NaN,NaN,NaN,2.83,3.69,2.44,2.75,3.70,2.38,2.80,3.50,2.30,2.95,3.80,2.47,2.81,3.63,2.42,1.67,2.15,1.69,2.26,1.73,2.31,1.68,2.22,0.25,1.81,2.09,1.79,2.13,1.81,2.17,1.77,2.08,2.63,3.40,2.63,2.60,3.5,2.60,NaN,NaN,NaN,2.67,3.59,2.67,2.60,3.75,2.55,2.55,3.6,2.63,2.70,3.75,2.80,2.63,3.58,2.64,1.70,2.10,1.72,2.20,1.78,2.34,1.68,2.23,0.00,1.95,1.95,1.96,1.96,1.97,1.99,1.94,1.94
661,E0,16/03/2024,17:30,Fulham,Tottenham,3,0,H,1,0,H,R Jones,16,14,7,5,9,10,4,5,2,3,0,0,3.50,3.80,1.95,3.30,3.80,2.00,NaN,NaN,NaN,3.42,4.09,2.01,3.40,4.00,1.95,3.40,3.75,1.95,3.54,4.16,2.08,3.40,3.93,2.01,1.48,2.60,1.50,2.70,1.52,2.72,1.49,2.62,0.50,1.89,2.01,1.89,2.02,1.93,2.05,1.86,2.00,3.25,4.00,2.00,3.25,3.9,2.00,NaN,NaN,NaN,3.45,4.00,2.05,3.25,4.00,2.00,3.40,3.9,2.00,3.51,4.10,2.13,3.34,3.94,2.05,1.44,2.70,1.49,2.72,1.50,2.84,1.47,2.72,0.50,1.86,2.04,1.88,2.05,1.90,2.11,1.83,2.04
662,E0,17/03/2024,14:00,West Ham,Aston Villa,1,1,D,1,0,H,J Gillett,13,13,5,5,13,12,7,11,3,3,0,0,2.63,3.75,2.45,2.65,3.70,2.45,NaN,NaN,NaN,2.66,3.82,2.52,2.60,3.75,2.45,2.60,3.50,2.45,2.75,3.92,2.58,2.65,3.73,2.51,1.57,2.35,1.58,2.50,1.63,2.55,1.56,2.44,0.00,2.01,1.89,2.01,1.90,2.04,1.91,1.99,1.88,2.38,3.75,2.80,2.40,3.5,2.80,NaN,NaN,NaN,2.48,3.69,2.83,2.50,3.75,2.62,2.40,3.7,2.75,2.50,3.80,2.88,2.45,3.63,2.77,1.57,2.35,1.63,2.42,1.63,2.50,1.58,2.39,0.00,1.83,2.10,1.84,2.10,1.85,2.12,1.82,2.06

# Selecting only match related columns. 

- Match Statistics (where available)
- Attendance = Crowd Attendance
- Referee = Match Referee
- HS = Home Team Shots
- AS = Away Team Shots
- HST = Home Team Shots on Target
- AST = Away Team Shots on Target
- HHW = Home Team Hit Woodwork
- AHW = Away Team Hit Woodwork
- HC = Home Team Corners
- AC = Away Team Corners
- HF = Home Team Fouls Committed
- AF = Away Team Fouls Committed
- HFKC = Home Team Free Kicks Conceded
- AFKC = Away Team Free Kicks Conceded
- HO = Home Team Offsides
- AO = Away Team Offsides
- HY = Home Team Yellow Cards
- AY = Away Team Yellow Cards
- HR = Home Team Red Cards
- AR = Away Team Red Cards
- HBP = Home Team Bookings Points (10 = yellow, 25 = red)
- ABP = Away Team Bookings Points (10 = yellow, 25 = red)

In [119]:
df = df[df.columns[:24]]
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,E0,05/08/2022,20:00,Crystal Palace,Arsenal,0,2,A,0,1,A,A Taylor,10,10,2,2,16,11,3,5,1,2,0,0
1,E0,06/08/2022,12:30,Fulham,Liverpool,2,2,D,1,0,H,A Madley,9,11,3,4,7,9,4,4,2,0,0,0
2,E0,06/08/2022,15:00,Bournemouth,Aston Villa,2,0,H,1,0,H,P Bankes,7,15,3,2,18,16,5,5,3,3,0,0
3,E0,06/08/2022,15:00,Leeds,Wolves,2,1,H,1,1,D,R Jones,12,15,4,6,13,9,6,4,2,0,0,0
4,E0,06/08/2022,15:00,Newcastle,Nott'm Forest,2,0,H,0,0,D,S Hooper,23,5,10,0,9,14,11,1,0,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658,E0,13/03/2024,19:30,Bournemouth,Luton,4,3,H,0,3,A,S Allison,24,8,10,4,16,11,11,3,1,2,0,0
659,E0,16/03/2024,15:00,Burnley,Brentford,2,1,H,1,0,H,D Bond,17,9,6,5,14,17,5,4,2,4,0,1
660,E0,16/03/2024,15:00,Luton,Nott'm Forest,1,1,D,0,1,A,D England,10,16,4,6,10,17,6,7,1,2,0,0
661,E0,16/03/2024,17:30,Fulham,Tottenham,3,0,H,1,0,H,R Jones,16,14,7,5,9,10,4,5,2,3,0,0
662,E0,17/03/2024,14:00,West Ham,Aston Villa,1,1,D,1,0,H,J Gillett,13,13,5,5,13,12,7,11,3,3,0,0

In [120]:
# we need:
# 1. A row for each match, from the pespective of both the home and away team.
# 2. A column called team_playing
# 3. A column for opponent

df['team_playing'] = df['HomeTeam']
df['opponent'] = df['AwayTeam']
df

/tmp/ipykernel_22259/1986281060.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['team_playing'] = df['HomeTeam']
/tmp/ipykernel_22259/1986281060.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['opponent'] = df['AwayTeam']

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,team_playing,opponent
0,E0,05/08/2022,20:00,Crystal Palace,Arsenal,0,2,A,0,1,A,A Taylor,10,10,2,2,16,11,3,5,1,2,0,0,Crystal Palace,Arsenal
1,E0,06/08/2022,12:30,Fulham,Liverpool,2,2,D,1,0,H,A Madley,9,11,3,4,7,9,4,4,2,0,0,0,Fulham,Liverpool
2,E0,06/08/2022,15:00,Bournemouth,Aston Villa,2,0,H,1,0,H,P Bankes,7,15,3,2,18,16,5,5,3,3,0,0,Bournemouth,Aston Villa
3,E0,06/08/2022,15:00,Leeds,Wolves,2,1,H,1,1,D,R Jones,12,15,4,6,13,9,6,4,2,0,0,0,Leeds,Wolves
4,E0,06/08/2022,15:00,Newcastle,Nott'm Forest,2,0,H,0,0,D,S Hooper,23,5,10,0,9,14,11,1,0,3,0,0,Newcastle,Nott'm Forest
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658,E0,13/03/2024,19:30,Bournemouth,Luton,4,3,H,0,3,A,S Allison,24,8,10,4,16,11,11,3,1,2,0,0,Bournemouth,Luton
659,E0,16/03/2024,15:00,Burnley,Brentford,2,1,H,1,0,H,D Bond,17,9,6,5,14,17,5,4,2,4,0,1,Burnley,Brentford
660,E0,16/03/2024,15:00,Luton,Nott'm Forest,1,1,D,0,1,A,D England,10,16,4,6,10,17,6,7,1,2,0,0,Luton,Nott'm Forest
661,E0,16/03/2024,17:30,Fulham,Tottenham,3,0,H,1,0,H,R Jones,16,14,7,5,9,10,4,5,2,3,0,0,Fulham,Tottenham
662,E0,17/03/2024,14:00,West Ham,Aston Villa,1,1,D,1,0,H,J Gillett,13,13,5,5,13,12,7,11,3,3,0,0,West Ham,Aston Villa

In [121]:
df2 = df.copy()
df2['team_playing'] = df2['AwayTeam']
df2['opponent'] = df2['HomeTeam']

df2

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,team_playing,opponent
0,E0,05/08/2022,20:00,Crystal Palace,Arsenal,0,2,A,0,1,A,A Taylor,10,10,2,2,16,11,3,5,1,2,0,0,Arsenal,Crystal Palace
1,E0,06/08/2022,12:30,Fulham,Liverpool,2,2,D,1,0,H,A Madley,9,11,3,4,7,9,4,4,2,0,0,0,Liverpool,Fulham
2,E0,06/08/2022,15:00,Bournemouth,Aston Villa,2,0,H,1,0,H,P Bankes,7,15,3,2,18,16,5,5,3,3,0,0,Aston Villa,Bournemouth
3,E0,06/08/2022,15:00,Leeds,Wolves,2,1,H,1,1,D,R Jones,12,15,4,6,13,9,6,4,2,0,0,0,Wolves,Leeds
4,E0,06/08/2022,15:00,Newcastle,Nott'm Forest,2,0,H,0,0,D,S Hooper,23,5,10,0,9,14,11,1,0,3,0,0,Nott'm Forest,Newcastle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658,E0,13/03/2024,19:30,Bournemouth,Luton,4,3,H,0,3,A,S Allison,24,8,10,4,16,11,11,3,1,2,0,0,Luton,Bournemouth
659,E0,16/03/2024,15:00,Burnley,Brentford,2,1,H,1,0,H,D Bond,17,9,6,5,14,17,5,4,2,4,0,1,Brentford,Burnley
660,E0,16/03/2024,15:00,Luton,Nott'm Forest,1,1,D,0,1,A,D England,10,16,4,6,10,17,6,7,1,2,0,0,Nott'm Forest,Luton
661,E0,16/03/2024,17:30,Fulham,Tottenham,3,0,H,1,0,H,R Jones,16,14,7,5,9,10,4,5,2,3,0,0,Tottenham,Fulham
662,E0,17/03/2024,14:00,West Ham,Aston Villa,1,1,D,1,0,H,J Gillett,13,13,5,5,13,12,7,11,3,3,0,0,Aston Villa,West Ham

In [122]:
df = pd.concat([df, df2], ignore_index=True)
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,team_playing,opponent
0,E0,05/08/2022,20:00,Crystal Palace,Arsenal,0,2,A,0,1,A,A Taylor,10,10,2,2,16,11,3,5,1,2,0,0,Crystal Palace,Arsenal
1,E0,06/08/2022,12:30,Fulham,Liverpool,2,2,D,1,0,H,A Madley,9,11,3,4,7,9,4,4,2,0,0,0,Fulham,Liverpool
2,E0,06/08/2022,15:00,Bournemouth,Aston Villa,2,0,H,1,0,H,P Bankes,7,15,3,2,18,16,5,5,3,3,0,0,Bournemouth,Aston Villa
3,E0,06/08/2022,15:00,Leeds,Wolves,2,1,H,1,1,D,R Jones,12,15,4,6,13,9,6,4,2,0,0,0,Leeds,Wolves
4,E0,06/08/2022,15:00,Newcastle,Nott'm Forest,2,0,H,0,0,D,S Hooper,23,5,10,0,9,14,11,1,0,3,0,0,Newcastle,Nott'm Forest
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1321,E0,13/03/2024,19:30,Bournemouth,Luton,4,3,H,0,3,A,S Allison,24,8,10,4,16,11,11,3,1,2,0,0,Luton,Bournemouth
1322,E0,16/03/2024,15:00,Burnley,Brentford,2,1,H,1,0,H,D Bond,17,9,6,5,14,17,5,4,2,4,0,1,Brentford,Burnley
1323,E0,16/03/2024,15:00,Luton,Nott'm Forest,1,1,D,0,1,A,D England,10,16,4,6,10,17,6,7,1,2,0,0,Nott'm Forest,Luton
1324,E0,16/03/2024,17:30,Fulham,Tottenham,3,0,H,1,0,H,R Jones,16,14,7,5,9,10,4,5,2,3,0,0,Tottenham,Fulham
1325,E0,17/03/2024,14:00,West Ham,Aston Villa,1,1,D,1,0,H,J Gillett,13,13,5,5,13,12,7,11,3,3,0,0,Aston Villa,West Ham

In [123]:
df['Date'] = pd.to_datetime(df['Date'])
df['Hour'] = df['Time'].apply(lambda x:x.split(":")[0])
df = df.sort_values(by= ['Date', 'Hour']).reset_index(drop = True)

/tmp/ipykernel_22259/1252534115.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df['Date'] = pd.to_datetime(df['Date'])

In [124]:
# Now we have a row for each match from the prespective of both the home and away team. 
# We need to create a binary column to indicate if a team is playing at home or not.

df['is_home'] = (df['HomeTeam'] == df['team_playing']).astype(int)
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,team_playing,opponent,Hour,is_home
0,E0,2022-01-09,20:00,Leicester,Man United,0,1,A,0,1,A,C Pawson,10,9,2,2,7,15,1,3,1,3,0,0,Leicester,Man United,20,1
1,E0,2022-01-09,20:00,Leicester,Man United,0,1,A,0,1,A,C Pawson,10,9,2,2,7,15,1,3,1,3,0,0,Man United,Leicester,20,0
2,E0,2022-01-10,12:30,Arsenal,Tottenham,3,1,H,1,1,D,A Taylor,22,7,9,3,10,10,5,2,2,1,0,1,Arsenal,Tottenham,12,1
3,E0,2022-01-10,12:30,Arsenal,Tottenham,3,1,H,1,1,D,A Taylor,22,7,9,3,10,10,5,2,2,1,0,1,Tottenham,Arsenal,12,0
4,E0,2022-01-10,15:00,Bournemouth,Brentford,0,0,D,0,0,D,T Bramall,7,13,1,4,11,10,7,8,1,2,0,0,Bournemouth,Brentford,15,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1321,E0,2024-11-03,20:00,Chelsea,Newcastle,3,2,H,1,1,D,J Brooks,12,11,8,3,12,7,0,4,3,1,0,0,Newcastle,Chelsea,20,0
1322,E0,2024-12-01,19:45,Burnley,Luton,1,1,D,1,0,H,T Harrington,13,14,7,5,7,12,2,8,1,0,0,0,Burnley,Luton,19,1
1323,E0,2024-12-01,19:45,Burnley,Luton,1,1,D,1,0,H,T Harrington,13,14,7,5,7,12,2,8,1,0,0,0,Luton,Burnley,19,0
1324,E0,2024-12-02,20:00,Crystal Palace,Chelsea,1,3,A,1,0,H,M Oliver,13,14,4,5,14,7,1,7,2,2,0,0,Crystal Palace,Chelsea,20,1
1325,E0,2024-12-02,20:00,Crystal Palace,Chelsea,1,3,A,1,0,H,M Oliver,13,14,4,5,14,7,1,7,2,2,0,0,Chelsea,Crystal Palace,20,0

In [125]:
# create a target column to indicate if the team_playing won that match or not. 
# 1 - win, 0 - loss and draw.
df['home_win'] = (df['FTHG']>df['FTAG']).astype(int)
df['away_win'] = (df['FTHG']<df['FTAG']).astype(int)
df['draw'] = (df['FTHG']==df['FTAG']).astype(int)
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,team_playing,opponent,Hour,is_home,home_win,away_win,draw
0,E0,2022-01-09,20:00,Leicester,Man United,0,1,A,0,1,A,C Pawson,10,9,2,2,7,15,1,3,1,3,0,0,Leicester,Man United,20,1,0,1,0
1,E0,2022-01-09,20:00,Leicester,Man United,0,1,A,0,1,A,C Pawson,10,9,2,2,7,15,1,3,1,3,0,0,Man United,Leicester,20,0,0,1,0
2,E0,2022-01-10,12:30,Arsenal,Tottenham,3,1,H,1,1,D,A Taylor,22,7,9,3,10,10,5,2,2,1,0,1,Arsenal,Tottenham,12,1,1,0,0
3,E0,2022-01-10,12:30,Arsenal,Tottenham,3,1,H,1,1,D,A Taylor,22,7,9,3,10,10,5,2,2,1,0,1,Tottenham,Arsenal,12,0,1,0,0
4,E0,2022-01-10,15:00,Bournemouth,Brentford,0,0,D,0,0,D,T Bramall,7,13,1,4,11,10,7,8,1,2,0,0,Bournemouth,Brentford,15,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1321,E0,2024-11-03,20:00,Chelsea,Newcastle,3,2,H,1,1,D,J Brooks,12,11,8,3,12,7,0,4,3,1,0,0,Newcastle,Chelsea,20,0,1,0,0
1322,E0,2024-12-01,19:45,Burnley,Luton,1,1,D,1,0,H,T Harrington,13,14,7,5,7,12,2,8,1,0,0,0,Burnley,Luton,19,1,0,0,1
1323,E0,2024-12-01,19:45,Burnley,Luton,1,1,D,1,0,H,T Harrington,13,14,7,5,7,12,2,8,1,0,0,0,Luton,Burnley,19,0,0,0,1
1324,E0,2024-12-02,20:00,Crystal Palace,Chelsea,1,3,A,1,0,H,M Oliver,13,14,4,5,14,7,1,7,2,2,0,0,Crystal Palace,Chelsea,20,1,0,1,0
1325,E0,2024-12-02,20:00,Crystal Palace,Chelsea,1,3,A,1,0,H,M Oliver,13,14,4,5,14,7,1,7,2,2,0,0,Chelsea,Crystal Palace,20,0,0,1,0

In [126]:
# target column is. if team_playing won the match then = 1 else 0

df['target'] = (((df['is_home'] == True) & (df['home_win'] == True)) | ((df['is_home'] == False) & (df['away_win'] == True))).astype(int)
# if is_home == 1 and home_win == 1 .apply(lambda x: 1 if (x['is_home']==1 & x['home_win']==1) else 0)then target == 1 
#df = df.drop(columns = ['Referee'])

In [135]:
df.sort_values(by = ['Date', 'Hour', 'Referee'], inplace = True)
df.drop(columns = ['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'Referee', 'home_win', 'away_win', 'draw']).columns
df[['team_playing', 'opponent', 'Hour', 'is_home', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST',
    'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'target']]

,team_playing,opponent,Hour,is_home,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR,target
0,Leicester,Man United,20,1,0,1,A,0,1,A,10,9,2,2,7,15,1,3,1,3,0,0,0
1,Man United,Leicester,20,0,0,1,A,0,1,A,10,9,2,2,7,15,1,3,1,3,0,0,1
2,Arsenal,Tottenham,12,1,3,1,H,1,1,D,22,7,9,3,10,10,5,2,2,1,0,1,1
3,Tottenham,Arsenal,12,0,3,1,H,1,1,D,22,7,9,3,10,10,5,2,2,1,0,1,0
7,Liverpool,Brighton,15,1,3,3,D,1,2,A,15,6,7,6,9,13,9,2,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1321,Newcastle,Chelsea,20,0,3,2,H,1,1,D,12,11,8,3,12,7,0,4,3,1,0,0,0
1322,Burnley,Luton,19,1,1,1,D,1,0,H,13,14,7,5,7,12,2,8,1,0,0,0,0
1323,Luton,Burnley,19,0,1,1,D,1,0,H,13,14,7,5,7,12,2,8,1,0,0,0,0
1324,Crystal Palace,Chelsea,20,1,1,3,A,1,0,H,13,14,4,5,14,7,1,7,2,2,0,0,0
1325,Chelsea,Crystal Palace,20,0,1,3,A,1,0,H,13,14,4,5,14,7,1,7,2,2,0,0,1

In [133]:
df.columns

Index(['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR',
       'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF',
       'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'team_playing', 'opponent', 'Hour',
       'is_home', 'home_win', 'away_win', 'draw', 'target'],
      dtype='object')